//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingStoreDesktop.Models.SystemModel
{
    using System;
    using System.Collections.Generic;

    public partial class DatLich : BaseModel
    {
        public string MaDL { get; set; }
        public string TenKH { get; set; }
        public string SoDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayCuoi { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.TimeSpan> ThoiGian { get; set; }
        public string GhiChu { get; set; }
        private Nullable<bool> _TrangThaiDuyet { get; set; }
        public Nullable<bool> TrangThaiDuyet { get => _TrangThaiDuyet; set { _TrangThaiDuyet = value; OnPropertyChanged(); } }
    }
}
